/* One-off generator: curates ~200 Medium/Hard interview DSA problems from the
   Personal Plan (PersonalDSARoadmap) + Most Asked sources, dropping easy ones,
   and emits src/Data/DSAPrep.js. Run with: node scripts/genDSAPrep.cjs */
const fs = require("fs");
const path = require("path");

const roadmap = require("../src/Data/PersonalDSARoadmap.json");

// Easy problems to exclude entirely (matched by exact Question name).
const DROP_EASY = new Set([
  "Two Sum",
  "Best Time to Buy and Sell Stock",
  "Range Sum Query - Immutable",
  "Valid Anagram",
  "Valid Palindrome II",
  "Longest Common Prefix",
  "Reverse Linked List",
  "Merge Two Sorted Lists",
  "Linked List Cycle",
  "Happy Number",
  "Intersection of Two Linked Lists",
  "Palindrome Linked List",
  "Valid Parentheses",
  "Implement Queue using Stacks",
  "Next Greater Element I",
  "Maximum Depth of Binary Tree",
  "Minimum Depth of Binary Tree",
  "Same Tree",
  "Symmetric Tree",
  "Invert Binary Tree",
  "Diameter of Binary Tree",
  "Balanced Binary Tree",
  "Convert Sorted Array to Binary Search Tree",
  "Last Stone Weight",
  "Binary Search",
  "Climbing Stairs",
  "Meeting Rooms",
  "Single Number",
  "Number of 1 Bits",
  "Counting Bits",
  "Missing Number",
  "Reverse Bits",
  "Power of Two",
  "Design HashMap",
  "Design HashSet",
  "Design Parking System",
  "Print in Order",
  "Plus One",
  "Sqrt(x)",
  "Roman to Integer",
]);

// Hard problems (everything else kept is treated as Medium).
const HARD = new Set([
  "Trapping Rain Water",
  "First Missing Positive",
  "Minimum Window Substring",
  "Sliding Window Maximum",
  "Reverse Nodes in k-Group",
  "Merge k Sorted Lists",
  "Largest Rectangle in Histogram",
  "Maximal Rectangle",
  "Binary Tree Maximum Path Sum",
  "Vertical Order Traversal of a Binary Tree",
  "Serialize and Deserialize Binary Tree",
  "Find Median from Data Stream",
  "Median of Two Sorted Arrays",
  "Split Array Largest Sum",
  "Word Break II",
  "Distinct Subsequences",
  "Regular Expression Matching",
  "Wildcard Matching",
  "Best Time to Buy and Sell Stock IV",
  "Burst Balloons",
  "Palindrome Partitioning II",
  "Longest Valid Parentheses",
  "Word Ladder",
  "Alien Dictionary",
  "Swim in Rising Water",
  "Word Search II",
  "N-Queens",
  "Sudoku Solver",
  "Longest Increasing Path in Matrix",
  "LFU Cache",
  "Design In-Memory File System",
]);

// Drop these (topic::name) to remove cross-topic duplicates (kept elsewhere).
const DROP_PAIRS = new Set([
  "Heap and Priority Queue::Merge k Sorted Lists",
  "Heap and Priority Queue::Meeting Rooms II",
  "Trie::Word Search II",
]);

// Display topic renames for cleaner section headers.
const TOPIC_RENAME = {
  "Greedy Algorithms": "Greedy & Intervals",
  "Mathematical and Number Theory": "Math & Number Theory",
};

function slugFromLink(link) {
  const m = link.match(/problems\/([^/]+)/);
  return m ? m[1] : null;
}

const out = [];
const seenSlugs = new Set();

for (const [srcTopic, problems] of Object.entries(roadmap)) {
  const topic = TOPIC_RENAME[srcTopic] || srcTopic;
  const kept = [];
  for (const q of problems) {
    if (DROP_EASY.has(q.Question)) continue;
    if (DROP_PAIRS.has(`${srcTopic}::${q.Question}`)) continue;
    const slug = slugFromLink(q.Question_link);
    if (!slug || seenSlugs.has(slug)) continue;
    seenSlugs.add(slug);
    kept.push({
      id: slug,
      title: q.Question,
      link: q.Question_link,
      difficulty: HARD.has(q.Question) ? "Hard" : "Medium",
    });
  }
  if (kept.length) out.push({ topic, problems: kept });
}

const total = out.reduce((a, t) => a + t.problems.length, 0);
const hard = out.reduce(
  (a, t) => a + t.problems.filter((p) => p.difficulty === "Hard").length,
  0
);

const header = `// Curated interview DSA set — ${total} quality Medium/Hard problems
// (${total - hard} Medium, ${hard} Hard), topic-organised.
// Sourced from the Personal Plan + Most Asked lists with easy problems removed.
// Generated by scripts/genDSAPrep.cjs — edit there and re-run, or edit directly.

export const DSA_TOPICS = ${JSON.stringify(out, null, 2)};

export const DSA_DIFFICULTY_CONFIG = {
  Medium:
    "bg-yellow-100 text-yellow-700 dark:bg-yellow-900/40 dark:text-yellow-300 border border-yellow-200 dark:border-yellow-800",
  Hard: "bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300 border border-red-200 dark:border-red-800",
};

// Flat list (id-keyed) for the Planning page picker and cross-page sync.
export const DSA_PROBLEMS = DSA_TOPICS.flatMap((t) =>
  t.problems.map((p) => ({ ...p, topic: t.topic }))
);

export const DSA_TOTAL = ${total};
`;

fs.writeFileSync(path.join(__dirname, "../src/Data/DSAPrep.js"), header);
console.log(`Wrote src/Data/DSAPrep.js — ${total} problems (${hard} Hard, ${total - hard} Medium) across ${out.length} topics`);
out.forEach((t) => console.log(`  ${t.topic}: ${t.problems.length}`));
